serial_test

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -10,6 +10,7 @@ BURN_LOC="$LOC/hw_test/tools/burnintest/64bit"
 CGUT_LOC="$LOC/hw_test/tools/cgutillx/cgutlcmd"
 DIO_LOC="$LOC/hw_test/tools/cgoslx-x64-1.03.029/CgosI2CgpioLoopback/Lx"
 EEUPDATE_LOC="$LOC/hw_test/tools/intel/Linux_x64/OEM_Mfg"
+SERIAL_LOC="$LOC/hw_test/tools/linux-serial-test"
 SCR_LOC="$LOC/hw_test"
 TMP_LOC="$LOC/hw_test/tmp"
 LIB_LOC="$LOC/hw_test/lib"
@@ -100,6 +101,31 @@ bi_log_copy(){
 burnintest_script(){
 	sudo rm /tmp/bi.log
 	sudo $BURN_LOC/bit_gui_x64 -S $BURN_LOC/script.bits
+}
+
+bios_rev_check(){
+	BIOS_REV=$(sudo $CGUT_LOC/cgutlcmd CGINFO /OT:BOARD /DUMP /BIOS | grep "System BIOS" | awk '{print $4}')
+	case $BIOS_REV in
+		QC31R128)
+			echo " " | tee -a $LOG_LOC/$SN_LOG.log
+			echo "****** Check BIOS Version is $BIOS_REV ******" | tee -a $LOG_LOC/$SN_LOG.log
+			fail_red_dialog "Check BIOS revision $BIOS_REV failed!"
+			;;
+		QC31R912)
+			echo " " | tee -a $LOG_LOC/$SN_LOG.log
+			echo "****** Check BIOS Version is $BIOS_REV ******" | tee -a $LOG_LOC/$SN_LOG.log
+			;;
+		QC32R128)
+			echo " " | tee -a $LOG_LOC/$SN_LOG.log
+			echo "****** Check BIOS Version is $BIOS_REV ******" | tee -a $LOG_LOC/$SN_LOG.log
+			fail_red_dialog "Check BIOS revision $BIOS_REV failed!"
+			;;
+		QC32R912)
+			echo " " | tee -a $LOG_LOC/$SN_LOG.log
+			echo "****** Check BIOS Version is $BIOS_REV ******" | tee -a $LOG_LOC/$SN_LOG.log
+			;;
+	esac
+			
 }
 
 bios_oem_update(){
@@ -473,9 +499,11 @@ pci_dev_check(){
 	echo "****** PCI device check!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	lspci |grep "$1" 
 	if [ $? = 0 ]; then
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check PCI dev $1 passed !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 		lspci |grep "$1" |tee -a $LOG_LOC/$SN_LOG.log
 	else
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check PCI dev $1 failed !  ******" | tee -a $LOG_LOC/$SN_LOG.log 
 		lspci |grep "$1" |tee -a $LOG_LOC/$SN_LOG.log
 		fail_red_dialog "Check PCI dev $1 failed !"
@@ -513,10 +541,24 @@ rs232_loop_test_old(){
 	exec 3<&- #free FD 3
 	LCHK=$(grep "5555AAAA" "$COM_LOG" )
 	if [ $LCHK == "5555AAAA" ]; then
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** RS232 port $1 loopback test passed!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** RS232 port $1 loopback test failed!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
 		fail_red_dialog "****** RS232 port $1 loopback test failed!  ******" 
+	fi
+}
+
+serial_loop_test(){
+	sudo $SERIAL_LOC/linux-serial-test -p $1 -b 115200 -o 1 -i 3
+	if [ $? = 0 ]; then
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** Check RS232 $1 loopback passed !  ******" | tee -a $LOG_LOC/$SN_LOG.log
+	else
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** Check RS232 $1 loopback failed !  ******" | tee -a $LOG_LOC/$SN_LOG.log 
+		fail_red_dialog "Check RS232 loopback $1 failed !"
 	fi
 }
 
@@ -526,8 +568,10 @@ serial_check(){
 	dmesg |grep serial: |grep $1 |tee -a $LOG_LOC/$SN_LOG.log
 	SERIAL=$(dmesg |grep serial: |grep $1 |awk '{print $4}')
 	if [ $SERIAL = $1 ] ; then
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check serial $SERIAL passed!, spec $1!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check serial $SERIAL failed!, spec $1!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
 		fail_red_dialog "****** Check serial $SERIAL failed!, spec $1!  ******"
 	fi
