update BI/232

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -5,17 +5,18 @@
 #For Debug
 #set -xv
 
-LOC="/data"
+LOC="/home/production"
 SCR_LOC="$LOC/hw_test"
 TMP_LOC="$LOC/hw_test/tmp"
 LIB_LOC="$LOC/hw_test/lib"
 LOG_LOC="$LOC/u7_log"
 MODEL_LOG="$LOC/hw_test/tmp/model.tmp"
-BURN_LOC="$LOC/tools/burnintest"
+BURN_LOC="$LOC/hw_test/tools/burnintest/64bit"
+BI_LOG=/tmp/bi.log
 
 #input spec of $1 BI to script ex.disk/nodisk $2 is BI time
 bi_cli_auto(){
-	BI_LOG=/tmp/BiTLog2.log
+	#BI_LOG=/tmp/BiTLog2.log
 
 	rm -f $BI_LOG
 	rm -f $BURN_LOC/cmdline_config.txt
@@ -41,7 +42,7 @@ bi_cli_auto(){
 		echo "****** BI time $RUN_T hour passed!, spec $2 mins! ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** BI time $RUN_T hour failed!, spec $2 mins!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "BI time $RUN_T hour failed!, spec $2 mins!"
 	fi
 	
 	BICHK=$(grep "TEST RUN PASSED" "$BI_LOG" | cut -c 10-15 )
@@ -49,15 +50,23 @@ bi_cli_auto(){
 		echo "****** Passmark BI result passed! ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** Passmark BI result failed!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "Passmark BI result failed!"
 	fi
 }
 
-
+bi_log_check(){
+ 	BICHK=$(grep "TEST RUN PASSED" "$BI_LOG" | cut -c 10-15 )
+        if [ $BICHK = "PASSED" ]; then
+                echo "****** Passmark BI result passed! ******" | tee -a $LOG_LOC/$SN_LOG.log
+        else
+                echo "****** Passmark BI result failed!  ******" | tee -a $LOG_LOC/$SN_LOG.log
+                fail_red_dialog "Passmark BI result failed!"
+        fi
+}
 
 bi_log_copy(){
 	#copy bi log to SN_log
-	BI_LOG=/tmp/BiTLog2.log
+	BI_LOG=/tmp/bi.log
 	echo " " | tee -a $LOG_LOC/$SN_LOG.log >/dev/null
 	echo " " | tee -a $LOG_LOC/$SN_LOG.log >/dev/null
 	echo " " | tee -a $LOG_LOC/$SN_LOG.log >/dev/null
@@ -75,80 +84,87 @@ cpu_temp_check(){
 	rm -r $TEMP_LOG
 	sensors -A | tee -a $TEMP_LOG
 	CPU_TEMP_LOG=$(sensors -A |grep "Core 0" |awk '{print $3}' |cut -c 1-3)
-	SYS_TEMP_LOG=$(sensors -A |grep "temp1" |awk '{print $2}' |cut -c 1-3)
+	#SYS_TEMP_LOG=$(sensors -A |grep "temp1" |awk '{print $2}' |cut -c 1-3)
 	#echo "****** Syetem temp $SYS_TEMP_LOG C !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 
 	if [ $CPU_TEMP_LOG -ge $1 ] && [ $CPU_TEMP_LOG -le $2 ];then
-		echo "****** CPU temp $CPU_TEMP_LOG C passed!, spec $1 - $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log	
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** CPU temp $CPU_TEMP_LOG C passed!, spec $1 to  $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log	
 	else
-		echo "****** CPU temp $CPU_TEMP_LOG C failed!, spec $1 - $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log
-		fail_red
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** CPU temp $CPU_TEMP_LOG C failed!, spec $1 to  $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log
+		fail_red_dialog "CPU temp $CPU_TEMP_LOG C failed!, spec $1 - $2 C"
 	fi
 }
 
-cpu_temp_check_cat(){
-	TEMP_LOG=$TMP_LOC/temp.tmp
-	rm -r $TEMP_LOG
-	sensors -A | tee -a $TEMP_LOG
-	sensors -A | grep "id 0" | tee -a $LOG_LOC/$SN_LOG.log
-	CPU_TEMP_LOG=$(cat /sys/class/hwmon/hwmon2/temp1_input | cut -c 1-2)
-	SYS_TEMP_LOG=$(cat /sys/class/hwmon/hwmon1/temp1_input | cut -c 1-2)
-	echo "****** Syetem temp $SYS_TEMP_LOG C !  ******" | tee -a $LOG_LOC/$SN_LOG.log
-	if [ $CPU_TEMP_LOG -ge $1 ] && [ $CPU_TEMP_LOG -le $2 ];then
-		echo "****** CPU temp $CPU_TEMP_LOG C passed!, spec $1 - $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log	
-	else
-		echo "****** CPU temp $CPU_TEMP_LOG C failed!, spec $1 - $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log
-		fail_red
-	fi
-}
 
-fail_red(){
-	#show big fail red
-	printf "\E[1;31;48m"
-	echo " ************************************************* "
-	echo " "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL "
-	echo " "
-	echo " ************************************************* "
-	printf "\E[0m"
-	echo ""
-	echo "****** TEST_FAILED! ****** " >> $LOG_LOC/$SN_LOG.log
-	mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-FAIL.log
-	read -p "Press Enter to end test" end
-	exit 1
+fail_red_dialog(){
+	dialog --title  TESTING_RESULT  --colors --yesno\
+	"\Zb\Z1FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL_FAIL\
+	 -------------------------------------------------\
+	 \Zn $1 \n\
+	Test again / Power off - 重新測試/關機（是/否）
+	" 20 55
+	#0=yes 1=no 255=Esc
+	response=$?
+	case $response in
+		0)
+		   echo "" >> $LOG_LOC/$SN_LOG.log
+	 	   echo "****** TEST_FAILED! ****** " >> $LOG_LOC/$SN_LOG.log
+		   mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-FAIL.log
+		   sh /home/production/hw_test/x.sh
+		exit 0 ;;
+	        
+		1) 
+		   echo "" >> $LOG_LOC/$SN_LOG.log
+	 	   echo "****** TEST_FAILED! ****** " >> $LOG_LOC/$SN_LOG.log
+		   mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-FAIL.log
+		   sync
+		   poweroff
+		exit 1 ;;
+		
+		255) 
+		   echo "" >> $LOG_LOC/$SN_LOG.log
+	 	   echo "****** TEST_FAILED! ****** " >> $LOG_LOC/$SN_LOG.log
+		   mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-FAIL.log
+		exit 255;;
+	esac
 }
 
 hwclock_check(){
-	BT=$(hwclock | cut -c 1-4)
+	#BT=$(echo "efco1234" | sudo -S hwclock | cut -c 1-4)
+	BT=$(sudo -S hwclock | cut -c 1-4)
 	if [ $BT = $1 ]; then
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check BIOS time $BT passed!, spec $1 !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check BIOS time $BT failed!, spec $1 !  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "Check BIOS time $BT failed!, spec $1 !"
 	fi
 }
 
 #1=device 2=mac_head 3=another mac_head
 lan_mac_check(){
 	echo " " | tee -a $LOG_LOC/$SN_LOG.log
-	echo "****** LAN MAC check!  ******" | tee -a $LOG_LOC/$SN_LOG.log
+	#echo "****** LAN MAC check!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	cat "/sys/class/net/$1/address"
 	if [ $? = 0 ];then
-		echo " " | tee -a $LOG_LOC/$SN_LOG.log
-		echo "****** Check $1 device !  ******" | tee -a $LOG_LOC/$SN_LOG.log
+		#echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		#echo "****** Check $1 device !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 		LAN=$1
 	else
-		echo " " | tee -a $LOG_LOC/$SN_LOG.log
-		echo "****** Check enp2s0 device !  ******" | tee -a $LOG_LOC/$SN_LOG.log
+		#echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		#echo "****** Check enp2s0 device !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 		LAN=enp2s0
 	fi
 	MAC=$(cat "/sys/class/net/$LAN/address")
@@ -157,7 +173,7 @@ lan_mac_check(){
 		echo "****** Check $LAN MAC $MAC passed!, spec $2 $3!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** Check $LAN MAC $MAC failed!, spec $2 $3!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "Check $LAN MAC $MAC failed!, spec $2 $3!"
 	fi
 }
 
@@ -179,7 +195,7 @@ eb_lan_down(){
 	else
 		echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check $1 ifdown fail !  ******" | tee -a $LOG_LOC/$SN_LOG.log
-		fail_red
+		fail_red_dialog "Check $1 ifdown fail !"
 	fi
 	
 }
@@ -194,7 +210,7 @@ lan_ping_check(){
 	else
 		echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check $1 ping $2 fail !  ******" | tee -a $LOG_LOC/$SN_LOG.log
-		fail_red
+		fail_red_dialog "Check $1 ping $2 fail !"
 	fi
 }
 
@@ -207,87 +223,77 @@ eb_lan_up(){
 	else
 		echo " " | tee -a $LOG_LOC/$SN_LOG.log
 		echo "****** Check $1 ifup fail !  ******" | tee -a $LOG_LOC/$SN_LOG.log
-		fail_red
+		fail_red_dialog "Check $1 ifup fail !" 
 	fi
 }
 
-pass_green(){
-	clear
-	echo "Serial Number:$SN "
-	#show big green pass
-	printf "\E[1;32;48m"
-	echo " ************************************************* "
-	echo " "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " "
-	echo " ************************************************* "
-	printf "\E[0m"
-	echo " " | tee -a $LOG_LOC/$SN_LOG.log
-	echo "****** ALL_TEST_PASSED! ****** " >> $LOG_LOC/$SN_LOG.log
-	mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-PASS.log
-	read -p "Press Enter to end test" end
-	exit 0
-}
+pass_green_dialog(){
+        dialog --title TESTING_RESULT --colors --yesno\
+        "\Zb\Z2PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+         PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+ 	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS\
+	 -------------------------------------------------\
+	 \ZnPower off the system - 系統關機（是/否）
+        " 20 55
 
-pass_green_poweroff(){
-	clear
-	echo "Serial Number:$SN "
-	#show big green pass
-	printf "\E[1;32;48m"
-	echo " ************************************************* "
-	echo " "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS_PASS "
-	echo " "
-	echo " ************************************************* "
-	printf "\E[0m"
-	echo " " | tee -a $LOG_LOC/$SN_LOG.log
-	echo "****** ALL_TEST_PASSED! ****** " >> $LOG_LOC/$SN_LOG.log
-	mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-PASS.log
-	sleep 2
-	poweroff
-	exit 0
+        #0=yes 1=no 255=Esc
+        response=$?
+        case $response in
+                0) 
+		   echo "" >> $LOG_LOC/$SN_LOG.log
+        	   echo "****** TEST_PASSED! ****** " >> $LOG_LOC/$SN_LOG.log
+        	   mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-PASS.log
+		   sync
+		   poweroff
+		exit 0;;
+                1) 
+		   echo "" >> $LOG_LOC/$SN_LOG.log
+        	   echo "****** TEST_PASSED! ****** " >> $LOG_LOC/$SN_LOG.log
+        	   mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-PASS.log
+		   echo "Bach to shell" 
+		exit 1;;
+                255) 
+		   echo "" >> $LOG_LOC/$SN_LOG.log
+        	   echo "****** TEST_PASSED! ****** " >> $LOG_LOC/$SN_LOG.log
+        	   mv $LOG_LOC/$SN_LOG.log $LOG_LOC/$SN_LOG-PASS.log
+		exit 255;;
+        esac
+}
+rs232_burnintest(){
+	sudo rm /tmp/bi.log
+	sudo $BURN_LOC/bit_gui_x64 -S $BURN_LOC/script.bits
 }
 
 rs232_loop_test(){
 	COM_LOG=$TMP_LOC/com.tmp
 	rm -r $COM_LOG
-	(stty raw; cat > $COM_LOG) < $1 &
+	(stty raw; cat > $COM_LOG )<$1 &
 	PID=$! #save PID to kill cat
 	echo "5555AAAA" > $1 # send command to serial port
 	sleep 5s # wait for response
 	kill $PID # kill cat process
+	EOF
 	LCHK=$(grep "5555AAAA" "$COM_LOG" )
 	if [ $LCHK == "5555AAAA" ]; then
 		echo "****** RS232 port $1 loopback test passed!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** RS232 port $1 loopback test failed!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "RS232 port $1 loopback test failed!" 
 	fi
 }
 
 rs232_loop_test_old(){
 	COM_LOG=$TMP_LOC/com.tmp
 	rm -r $COM_LOG
-	stty -F $1 115200 raw -echo #config serial port
-	exec 3<$1 #redirect serial output to FD 3
+	sudo stty -F $1 115200 raw -echo #config serial port
+	sudo exec 3<$1 #redirect serial output to FD 3
 	cat <&3 > $COM_LOG & #redirect serial output to file
 	PID=$! #save PID to kill cat
 	echo "5555AAAA" > $1 # send command to serial port
@@ -299,7 +305,7 @@ rs232_loop_test_old(){
 		echo "****** RS232 port $1 loopback test passed!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** RS232 port $1 loopback test failed!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "****** RS232 port $1 loopback test failed!  ******" 
 	fi
 }
 
@@ -312,7 +318,7 @@ serial_check(){
 		echo "****** Check serial $SERIAL passed!, spec $1!  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** Check serial $SERIAL failed!, spec $1!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "****** Check serial $SERIAL failed!, spec $1!  ******"
 	fi
 }
 
@@ -341,7 +347,7 @@ usb_dev_check (){
 		echo "****** Check USB dev $1 passed !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** Check USB dev $1 failed !  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "****** Check USB dev $1 failed !  ******"
 	fi
 }
 
@@ -355,7 +361,7 @@ usb_id_check (){
 		echo "****** Check USB ID $1 passed !  ******" | tee -a $LOG_LOC/$SN_LOG.log
 	else
 		echo "****** Check USB ID $1 failed !  ******" | tee -a $LOG_LOC/$SN_LOG.log 
-		fail_red
+		fail_red_dialog "****** Check USB ID $1 failed !  ******" 
 	fi
 }
 
