bi

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -48,15 +48,15 @@ at_check(){
 }
 
 bi_stress(){
-	sum=0
+	sum=$(($3/10))
         i=0
-        while [ $i -lt $3 ]
+	count=0
+	sudo stress-ng --cpu 4 --vm 1 --vm-bytes 1G --timeout $3m --metrics-brief &
+        while [ $i -lt $sum ]
         do
                 i=$(($i+1))
 		clear
-		echo "BI run $i, Total $3"
-            	uptime 
-		sudo stress-ng --cpu 4 --vm 1 --vm-bytes 1G --timeout 10m --metrics-brief 
+		echo "BI run $i, Total $sum"
 		if [ $? = 0 ];then
 			UPTIME_LOG=$(uptime)
         		CPU_TEMP_LOG=$(sensors -A |grep "Core 0" |awk '{print $3}' |cut -c 1-3)
@@ -66,19 +66,69 @@ bi_stress(){
                 			echo "Check CPU temp $CPU_TEMP_LOG C failed! spec $1 to $2 C" | tee -a $LOG_LOC/$SN_LOG.log
                 			fail_red_dialog "Check CPU temp $CPU_TEMP_LOG C failed! spec $1 - $2 C"
         			fi
-			sleep 5
+			sleep 10m
+			count=$(($count+10))
         	else
                		echo "- Check BI failed!" | tee -a $LOG_LOC/$SN_LOG.log
                	    	fail_red_dialog "Check BI failed!"
         	fi
-
-                #sum=$(($sum+$MIC_CHECK))
         done
-	if [ $i != $3 ];then
-               		echo "- Check BI $i run failed! spec $i" | tee -a $LOG_LOC/$SN_LOG.log
-               	    	fail_red_dialog "Check BI run $i failed! spec $i"
+	
+        echo "$UPTIME_LOG , Check CPU temp $CPU_TEMP_LOG C passed! spec $1 to $2 C" | tee -a $LOG_LOC/$SN_LOG.log
+	
+	if [ $count -ge $3 ];then
+               		echo "- Check BI time $count passed! spec $3" | tee -a $LOG_LOC/$SN_LOG.log
+	else               		
+			echo "- Check BI time $count failed! spec $3" | tee -a $LOG_LOC/$SN_LOG.log
+               	    	fail_red_dialog "Check BI time $BI_TOTAL failed! spec $3"
 	fi
 }
+
+bi_stress_com(){
+        sum=$(($3/10))
+        i=0
+        count=0
+        sudo stress-ng --cpu 4 --vm 1 --vm-bytes 1G --timeout $3m --metrics-brief &
+        while [ $i -lt $sum ]
+        do
+                i=$(($i+1))
+                clear
+                echo "BI run $i, Total $sum"
+                if [ $? = 0 ];then
+                        UPTIME_LOG=$(uptime)
+                        CPU_TEMP_LOG=$(sensors -A |grep "Core 0" |awk '{print $3}' |cut -c 1-3)
+                                if [ $CPU_TEMP_LOG -ge $1 ] && [ $CPU_TEMP_LOG -le $2 ];then
+                                        echo "$UPTIME_LOG , Check CPU temp $CPU_TEMP_LOG C passed! spec $1 to $2 C" | tee -a $LOG_LOC/$SN_LOG.log
+                                else
+                                        echo "Check CPU temp $CPU_TEMP_LOG C failed! spec $1 to $2 C" | tee -a $LOG_LOC/$SN_LOG.log
+                                        fail_red_dialog "Check CPU temp $CPU_TEMP_LOG C failed! spec $1 - $2 C"
+                                fi
+                        #sleep 10m
+			#run serial loopback test for 600 secs
+			sudo $SERIAL_LOC/serial-test -s -e -p /dev/ttyS0 -b 115200 -o 599 -i 600
+				if [ $? = 0 ]; then
+					echo "- Check RS232 run $i loopback passed !" | tee -a $LOG_LOC/$SN_LOG.log
+				else
+					echo "- Check RS232 run $i loopback failed !" | tee -a $LOG_LOC/$SN_LOG.log 
+					fail_red_dialog "Check RS232-$i loopback failed !"
+				fi
+                        count=$(($count+10))
+                else
+                        echo "- Check BI failed!" | tee -a $LOG_LOC/$SN_LOG.log
+                        fail_red_dialog "Check BI failed!"
+                fi
+        done
+
+        echo "$UPTIME_LOG , Check CPU temp $CPU_TEMP_LOG C passed! spec $1 to $2 C" | tee -a $LOG_LOC/$SN_LOG.log
+
+        if [ $count -ge $3 ];then
+                        echo "- Check BI time $count passed! spec $3" | tee -a $LOG_LOC/$SN_LOG.log
+        else
+                        echo "- Check BI time $count failed! spec $3" | tee -a $LOG_LOC/$SN_LOG.log
+                        fail_red_dialog "Check BI time $BI_TOTAL failed! spec $3"
+        fi
+}
+
 
 #input spec of $1 BI to script ex.disk/nodisk $2 is BI time
 bi_cli_auto(){
