add mic test

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -47,6 +47,41 @@ at_check(){
         fi
 }
 
+bi_stress(){
+	cpu_temp_check +30 +95
+
+	sum=0
+        i=0
+        while [ $i -lt 6 ]
+        do
+                i=$(($i+1))
+		sudo stress-ng --cpu 4 --vm 1 --vm-bytes 1G --timeout 10s --metrics-brief
+			if [ $? = 0 ];then
+                		echo "****** Check AT $3 passed! ******" | tee -a $LOG_LOC/$SN_LOG.log
+                		sudo killall -9 cat
+        		else
+                		echo "****** Check AT $(cat $AT_LOG | grep $3) failed! ******" | tee -a $LOG_LOC/$SN_LOG.log
+                		sudo killall -9 cat
+                		fail_red_dialog "Check AT $(cat $AT_LOG | grep $3) failed!"
+        		fi
+
+                sum=$(($sum+$MIC_CHECK))
+        #       echo $MIC_CHECK
+        #       sleep 1
+        done
+        #       clear   
+        #       echo $sum
+        #       sleep 5
+
+        if [ $sum -ge $1 ] ;then
+                echo "****** Check MIC sum is $sum  passed!, spec $1  ******" | tee -a $LOG_LOC/$SN_LOG.log
+        else
+                echo "****** Check MIC sum is $sum  failed!, spec $1  ******" | tee -a $LOG_LOC/$SN_LOG.log
+                fail_red_dialog "Check MIC sum $sum failed!, spec $1"
+        fi
+
+}
+
 #input spec of $1 BI to script ex.disk/nodisk $2 is BI time
 bi_cli_auto(){
 	#BI_LOG=/tmp/BiTLog2.log
@@ -216,8 +251,6 @@ cpu_temp_check(){
 	sensors -A | tee -a $TEMP_LOG
 	CPU_TEMP_LOG=$(sensors -A |grep "Core 0" |awk '{print $3}' |cut -c 1-3)
 	#SYS_TEMP_LOG=$(sensors -A |grep "temp1" |awk '{print $2}' |cut -c 1-3)
-	#echo "****** Syetem temp $SYS_TEMP_LOG C !  ******" | tee -a $LOG_LOC/$SN_LOG.log
-
 	if [ $CPU_TEMP_LOG -ge $1 ] && [ $CPU_TEMP_LOG -le $2 ];then
 		echo "****** Check CPU temp $CPU_TEMP_LOG C passed!, spec $1 to  $2 C  ******" | tee -a $LOG_LOC/$SN_LOG.log	
 	else
