u7300-ls

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -321,6 +321,17 @@ bios_rev_check(){
 	fi
 }
 
+
+bios_sn_check(){
+	BIOS_SN=$(sudo $CGUT_LOC/cgutlcmd CGINFO /OT:BOARD /DUMP | grep "Serial Number" | awk '{print $3}')
+	if [ $? = 0 ] ; then
+		echo "- Check BIOS Serial Number is $BIOS_SN !" | tee -a $LOG_LOC/$SN_LOG.log
+	else
+		echo "****** Check BIOS Serial Number  $BIOS_SN failed!  ******" | tee -a $LOG_LOC/$SN_LOG.log 
+		fail_red_dialog "Check BIOS Serial Number $BIOS_SN failed!"
+	fi
+}
+
 bios_oem_check(){
 	OEM_REV=$(sudo $CGUT_LOC/cgutlcmd CGINFO /OT:BOARD /DUMP /BIOS | grep OEM | awk '{print $4}')
 	if [ $OEM_REV = $1 ] || [ $OEM_REV = $2 ]; then
