u7

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -347,6 +347,18 @@ bios_oem_update(){
 			sudo $CGUT_LOC/cgutlcmd MODULE /OT:BOARD /OEM:$OEM
 			bios_oem_check $OEM
 			;;
+		QA50R151)
+			OEM=QA50W151
+			sudo $CGUT_LOC/cgutlcmd MODULE /OT:BOARD /ADD /IF:$CGUT_LOC/$OEM.MOD
+				if [ $? = 0 ];then
+					echo "-BIOS default $OEM update passed!" | tee -a $LOG_LOC/$SN_LOG.log
+        			else
+					echo "****** BIOS defualt $OEM update failed! ******" | tee -a $LOG_LOC/$SN_LOG.log
+					fail_red_dialog "BIOS default $OEM update failed!"
+        			fi
+			sudo $CGUT_LOC/cgutlcmd MODULE /OT:BOARD /OEM:$OEM
+			bios_oem_check $OEM
+			;;
 	esac
 			
 }
