webctrl

diff --git a/u7_func b/u7_func
--- a/u7_func
+++ b/u7_func
@@ -12,8 +12,11 @@ LIB_LOC="$LOC/hw_test/lib"
 LOG_LOC="$LOC/u7_log"
 MODEL_LOG="$LOC/hw_test/tmp/model.tmp"
 BURN_LOC="$LOC/hw_test/tools/burnintest/64bit"
-BI_LOG=/tmp/bi.log
+BI_LOG="/tmp/bi.log"
+MIC_LOG="$LOC/hw_test/tmp/mic.tmp"
 USB30_LOC="$LOC/hw_test/tmp/usb30.tmp"
+DIO_LOG="$LOC/hw_test/tmp/dio.tmp"
+DIO_LOC="$LOC/hw_test/tools/cgoslx-x64-1.03.029/CgosI2CgpioLoopback/Lx"
 
 #input spec of $1 BI to script ex.disk/nodisk $2 is BI time
 bi_cli_auto(){
@@ -110,6 +113,19 @@ cpu_temp_check(){
 	fi
 }
 
+dio_loopback_test(){
+	echo " " | tee -a $LOG_LOC/$SN_LOG.log
+        echo "****** DIO Loopback Test!  ******" | tee -a $LOG_LOC/$SN_LOG.log
+	$DIO_LOC/cgosi2cgpioloopback > $DIO_LOG
+	if [ $? = 0 ];then
+                echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "******  $(cat $DIO_LOG)  ******" | tee -a $LOG_LOC/$SN_LOG.log
+        else
+                echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** $(cat $DIO_LOG)  ******" | tee -a $LOG_LOC/$SN_LOG.log
+		fail_red_dialog "DIO Loopback $(cat $DIO_LOG) failed!"
+        fi
+}
 
 fail_red_dialog(){
 	dialog --title  TESTING_RESULT  --colors --yesno\
@@ -239,6 +255,20 @@ eb_lan_up(){
 		fail_red_dialog "Check $1 ifup fail !" 
 	fi
 }
+
+mic_test(){
+	arecord -d 3 -vv -f dat /dev/null 2> $MIC_LOG
+	MIC_CHECK=$( tail -1 $MIC_LOG | awk '{print $NF}' | cut -c 1-2)
+	if [ $MIC_CHECK -ge $1 ] ;then
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** MIC check $MIC_CHECK % passed!, spec $1 %  ******" | tee -a $LOG_LOC/$SN_LOG.log	
+	else
+	        echo " " | tee -a $LOG_LOC/$SN_LOG.log
+		echo "****** MIC check $MIC_CHECK % failed!, spec $1 %  ******" | tee -a $LOG_LOC/$SN_LOG.log	
+		fail_red_dialog "MIC check $MIC_CHECK % failed!, spec $1 %"	
+	fi
+}
+
 
 pass_green_dialog(){
         dialog --title TESTING_RESULT --colors --yesno\
